apiVersion: v1
kind: Service
metadata:
  name: kafka2
  labels:
    app: kafka2
    component: kafka-broker2
spec:
  ports:
  - port: 9092
    name: kafka-port
    targetPort: 9092
    protocol: TCP
  selector:
    app: kafka2
    component: kafka-broker2
  type: LoadBalancer
