apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: kafka2
    component: kafka-broker2
  name: kafka-broker2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka2
        component: kafka-broker2
    spec:
      containers:
      - name: kafka2
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          valueFrom:
              fieldRef:
                fieldPath: status.podIP
        - name: KAFKA_ADVERTISED_LISTENERS
          valueFrom:
              fieldRef:
                fieldPath: status.podIP
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: kafka-zoo-svc:2181
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_CREATE_TOPICS
          value: "taxi-data:4:1,throughput:2:1,piped-taxi-data:2:1,most-freq-driven:2:1,turnover:2:1"
