package constants;

import java.util.HashMap;
import java.util.Map;

public class Locations {
	public static final Map<String, String> locations = createMap();
	private static Map<String, String> createMap()
	{
		Map<String,String> locations = new HashMap<String,String>();
		
		locations.put("1", "Newark Airport");
		locations.put("2", "Jamaica Bay");
		locations.put("3", "Allerton/Pelham Gardens");
		locations.put("4", "Alphabet City");
		locations.put("5", "Arden Heights");
		locations.put("6", "Arrochar/Fort Wadsworth");
		locations.put("7", "Astoria");
		locations.put("8", "Astoria Park");
		locations.put("9", "Auburndale");
		locations.put("10", "Baisley Park");
		locations.put("11", "Bath Beach");
		locations.put("12", "Battery Park");
		locations.put("13", "Battery Park City");
		locations.put("14", "Bay Ridge");
		locations.put("15", "Bay Terrace/Fort Totten");
		locations.put("16", "Bayside");
		locations.put("17", "Bedford");
		locations.put("18", "Bedford Park");
		locations.put("19", "Bellerose");
		locations.put("20", "Belmont");
		locations.put("21", "Bensonhurst East");
		locations.put("22", "Bensonhurst West");
		locations.put("23", "Bloomfield/Emerson Hill");
		locations.put("24", "Bloomingdale");
		locations.put("25", "Boerum Hill");
		locations.put("26", "Borough Park");
		locations.put("27", "Breezy Point/Fort Tilden/Riis Beach");
		locations.put("28", "Briarwood/Jamaica Hills");
		locations.put("29", "Brighton Beach");
		locations.put("30", "Broad Channel");
		locations.put("31", "Bronx Park");
		locations.put("32", "Bronxdale");
		locations.put("33", "Brooklyn Heights");
		locations.put("34", "Brooklyn Navy Yard");
		locations.put("35", "Brownsville");
		locations.put("36", "Bushwick North");
		locations.put("37", "Bushwick South");
		locations.put("38", "Cambria Heights");
		locations.put("39", "Canarsie");
		locations.put("40", "Carroll Gardens");
		locations.put("41", "Central Harlem");
		locations.put("42", "Central Harlem North");
		locations.put("43", "Central Park");
		locations.put("44", "Charleston/Tottenville");
		locations.put("45", "Chinatown");
		locations.put("46", "City Island");
		locations.put("47", "Claremont/Bathgate");
		locations.put("48", "Clinton East");
		locations.put("49", "Clinton Hill");
		locations.put("50", "Clinton West");
		locations.put("51", "Co-Op City");
		locations.put("52", "Cobble Hill");
		locations.put("53", "College Point");
		locations.put("54", "Columbia Street");
		locations.put("55", "Coney Island");
		locations.put("56", "Corona");
		locations.put("57", "Corona");
		locations.put("58", "Country Club");
		locations.put("59", "Crotona Park");
		locations.put("60", "Crotona Park East");
		locations.put("61", "Crown Heights North");
		locations.put("62", "Crown Heights South");
		locations.put("63", "Cypress Hills");
		locations.put("64", "Douglaston");
		locations.put("65", "Downtown Brooklyn/MetroTech");
		locations.put("66", "DUMBO/Vinegar Hill");
		locations.put("67", "Dyker Heights");
		locations.put("68", "East Chelsea");
		locations.put("69", "East Concourse/Concourse Village");
		locations.put("70", "East Elmhurst");
		locations.put("71", "East Flatbush/Farragut");
		locations.put("72", "East Flatbush/Remsen Village");
		locations.put("73", "East Flushing");
		locations.put("74", "East Harlem North");
		locations.put("75", "East Harlem South");
		locations.put("76", "East New York");
		locations.put("77", "East New York/Pennsylvania Avenue");
		locations.put("78", "East Tremont");
		locations.put("79", "East Village");
		locations.put("80", "East Williamsburg");
		locations.put("81", "Eastchester");
		locations.put("82", "Elmhurst");
		locations.put("83", "Elmhurst/Maspeth");
		locations.put("84", "Eltingville/Annadale/Prince's Bay");
		locations.put("85", "Erasmus");
		locations.put("86", "Far Rockaway");
		locations.put("87", "Financial District North");
		locations.put("88", "Financial District South");
		locations.put("89", "Flatbush/Ditmas Park");
		locations.put("90", "Flatiron");
		locations.put("91", "Flatlands");
		locations.put("92", "Flushing");
		locations.put("93", "Flushing Meadows-Corona Park");
		locations.put("94", "Fordham South");
		locations.put("95", "Forest Hills");
		locations.put("96", "Forest Park/Highland Park");
		locations.put("97", "Fort Greene");
		locations.put("98", "Fresh Meadows");
		locations.put("99", "Freshkills Park");
		locations.put("100", "Garment District");
		locations.put("101", "Glen Oaks");
		locations.put("102", "Glendale");
		locations.put("103", "Governor's Island/Ellis Island/Liberty Island");
		locations.put("104", "Governor's Island/Ellis Island/Liberty Island");
		locations.put("105", "Governor's Island/Ellis Island/Liberty Island");
		locations.put("106", "Gowanus");
		locations.put("107", "Gramercy");
		locations.put("108", "Gravesend");
		locations.put("109", "Great Kills");
		locations.put("110", "Great Kills Park");
		locations.put("111", "Green-Wood Cemetery");
		locations.put("112", "Greenpoint");
		locations.put("113", "Greenwich Village North");
		locations.put("114", "Greenwich Village South");
		locations.put("115", "Grymes Hill/Clifton");
		locations.put("116", "Hamilton Heights");
		locations.put("117", "Hammels/Arverne");
		locations.put("118", "Heartland Village/Todt Hill");
		locations.put("119", "Highbridge");
		locations.put("120", "Highbridge Park");
		locations.put("121", "Hillcrest/Pomonok");
		locations.put("122", "Hollis");
		locations.put("123", "Homecrest");
		locations.put("124", "Howard Beach");
		locations.put("125", "Hudson Sq");
		locations.put("126", "Hunts Point");
		locations.put("127", "Inwood");
		locations.put("128", "Inwood Hill Park");
		locations.put("129", "Jackson Heights");
		locations.put("130", "Jamaica");
		locations.put("131", "Jamaica Estates");
		locations.put("132", "JFK Airport");
		locations.put("133", "Kensington");
		locations.put("134", "Kew Gardens");
		locations.put("135", "Kew Gardens Hills");
		locations.put("136", "Kingsbridge Heights");
		locations.put("137", "Kips Bay");
		locations.put("138", "LaGuardia Airport");
		locations.put("139", "Laurelton");
		locations.put("140", "Lenox Hill East");
		locations.put("141", "Lenox Hill West");
		locations.put("142", "Lincoln Square East");
		locations.put("143", "Lincoln Square West");
		locations.put("144", "Little Italy/NoLiTa");
		locations.put("145", "Long Island City/Hunters Point");
		locations.put("146", "Long Island City/Queens Plaza");
		locations.put("147", "Longwood");
		locations.put("148", "Lower East Side");
		locations.put("149", "Madison");
		locations.put("150", "Manhattan Beach");
		locations.put("151", "Manhattan Valley");
		locations.put("152", "Manhattanville");
		locations.put("153", "Marble Hill");
		locations.put("154", "Marine Park/Floyd Bennett Field");
		locations.put("155", "Marine Park/Mill Basin");
		locations.put("156", "Mariners Harbor");
		locations.put("157", "Maspeth");
		locations.put("158", "Meatpacking/West Village West");
		locations.put("159", "Melrose South");
		locations.put("160", "Middle Village");
		locations.put("161", "Midtown Center");
		locations.put("162", "Midtown East");
		locations.put("163", "Midtown North");
		locations.put("164", "Midtown South");
		locations.put("165", "Midwood");
		locations.put("166", "Morningside Heights");
		locations.put("167", "Morrisania/Melrose");
		locations.put("168", "Mott Haven/Port Morris");
		locations.put("169", "Mount Hope");
		locations.put("170", "Murray Hill");
		locations.put("171", "Murray Hill-Queens");
		locations.put("172", "New Dorp/Midland Beach");
		locations.put("173", "North Corona");
		locations.put("174", "Norwood");
		locations.put("175", "Oakland Gardens");
		locations.put("176", "Oakwood");
		locations.put("177", "Ocean Hill");
		locations.put("178", "Ocean Parkway South");
		locations.put("179", "Old Astoria");
		locations.put("180", "Ozone Park");
		locations.put("181", "Park Slope");
		locations.put("182", "Parkchester");
		locations.put("183", "Pelham Bay");
		locations.put("184", "Pelham Bay Park");
		locations.put("185", "Pelham Parkway");
		locations.put("186", "Penn Station/Madison Sq West");
		locations.put("187", "Port Richmond");
		locations.put("188", "Prospect-Lefferts Gardens");
		locations.put("189", "Prospect Heights");
		locations.put("190", "Prospect Park");
		locations.put("191", "Queens Village");
		locations.put("192", "Queensboro Hill");
		locations.put("193", "Queensbridge/Ravenswood");
		locations.put("194", "Randalls Island");
		locations.put("195", "Red Hook");
		locations.put("196", "Rego Park");
		locations.put("197", "Richmond Hill");
		locations.put("198", "Ridgewood");
		locations.put("199", "Rikers Island");
		locations.put("200", "Riverdale/North Riverdale/Fieldston");
		locations.put("201", "Rockaway Park");
		locations.put("202", "Roosevelt Island");
		locations.put("203", "Rosedale");
		locations.put("204", "Rossville/Woodrow");
		locations.put("205", "Saint Albans");
		locations.put("206", "Saint George/New Brighton");
		locations.put("207", "Saint Michaels Cemetery/Woodside");
		locations.put("208", "Schuylerville/Edgewater Park");
		locations.put("209", "Seaport");
		locations.put("210", "Sheepshead Bay");
		locations.put("211", "SoHo");
		locations.put("212", "Soundview/Bruckner");
		locations.put("213", "Soundview/Castle Hill");
		locations.put("214", "South Beach/Dongan Hills");
		locations.put("215", "South Jamaica");
		locations.put("216", "South Ozone Park");
		locations.put("217", "South Williamsburg");
		locations.put("218", "Springfield Gardens North");
		locations.put("219", "Springfield Gardens South");
		locations.put("220", "Spuyten Duyvil/Kingsbridge");
		locations.put("221", "Stapleton");
		locations.put("222", "Starrett City");
		locations.put("223", "Steinway");
		locations.put("224", "Stuy Town/Peter Cooper Village");
		locations.put("225", "Stuyvesant Heights");
		locations.put("226", "Sunnyside");
		locations.put("227", "Sunset Park East");
		locations.put("228", "Sunset Park West");
		locations.put("229", "Sutton Place/Turtle Bay North");
		locations.put("230", "Times Sq/Theatre District");
		locations.put("231", "TriBeCa/Civic Center");
		locations.put("232", "Two Bridges/Seward Park");
		locations.put("233", "UN/Turtle Bay South");
		locations.put("234", "Union Sq");
		locations.put("235", "University Heights/Morris Heights");
		locations.put("236", "Upper East Side North");
		locations.put("237", "Upper East Side South");
		locations.put("238", "Upper West Side North");
		locations.put("239", "Upper West Side South");
		locations.put("240", "Van Cortlandt Park");
		locations.put("241", "Van Cortlandt Village");
		locations.put("242", "Van Nest/Morris Park");
		locations.put("243", "Washington Heights North");
		locations.put("244", "Washington Heights South");
		locations.put("245", "West Brighton");
		locations.put("246", "West Chelsea/Hudson Yards");
		locations.put("247", "West Concourse");
		locations.put("248", "West Farms/Bronx River");
		locations.put("249", "West Village");
		locations.put("250", "Westchester Village/Unionport");
		locations.put("251", "Westerleigh");
		locations.put("252", "Whitestone");
		locations.put("253", "Willets Point");
		locations.put("254", "Williamsbridge/Olinville");
		locations.put("255", "Williamsburg (North Side)");
		locations.put("256", "Williamsburg (South Side)");
		locations.put("257", "Windsor Terrace");
		locations.put("258", "Woodhaven");
		locations.put("259", "Woodlawn/Wakefield");
		locations.put("260", "Woodside");
		locations.put("261", "World Trade Center");
		locations.put("262", "Yorkville East");
		locations.put("263", "Yorkville West");
		locations.put("264", "NV");
		locations.put("265", "NA");

		return locations;
	}
}
